<h1>ANIMATED MEDIA - DIGITAL SIGNAGE - AN OVERVIEW</h1>
<p>More and more entrepreneurs have noticed that animated digital information increases sales and promotes the producer's profile. The same medium is often used in a social context by ticket-sellers, game parlours, banks, and representatives of many other fields of business. Thoroughly analysed results from around the world prove a clear sales advantage. It is important to keep in mind that the overall drop in sales has made investments into hardware more profitable. The software we provide guarantees the consistency of the data thus presented; the product is always ready to be upgraded and updated fast and in a manner easily understood by anyone.<br />
<br />
Purveyors of hardware never tire of praising their products, while acquiring bigger and bigger market shares in an increasingly aggressive manner. The advertising industry's zeal for providing more exciting and diverse solutions is unquenchable. Thus our new medium, bringing together the endless possibilities of both hardware and advertising, is capable of effectively taking advantage of all modern tools in the best possible manner and according to the client's wishes.<br />
<br />
THE NEW MEDIUM, like any other channel for advertising, strives to amass additional value. In this context, information is more important than technology.</p>

<h1>THE GOAL</h1>
<p>You're welcome to observe the new media channel!<br />
<br />
Years ago, one could buy bread that was simply that -- bread. Nowadays sales do not work this way; life has moved on. The client's wish has become the producer's command; competition for the consumer's attention has grown dramatically fiercer. Thus, making sure that consumers receive relevant information is of key strategic importance in the current market. Manufacturers and vendors need to foresee the buyers' needs, while at the same time finding an easily accessible means of communication that matches the very same needs. Brand awareness, for example, has grown remarkably in recent times. The value of the brand, though, is mostly created via active advertising: the right information needs to reach the consumer at the right time. This can happen in a variety of ways, but lately the importance of guiding the client at the very spot where they make the decision has generally been understood. The modern media soup drenches us everywhere we go, thus targeted information works the best where the consumers go the most, i.e. in shopping malls, cafés and other locations actively frequented by multitudes of people. Such behaviour can fancifully be called “last meter marketing”.<br />
<br />
The idea of the new data channel, of the medium of animated signage, is based on the concept of directly influencing the consumer's preferences.</p>

<h1>SCREENWERK'S POSSIBILITIES</h1> 
<p>The number and technical indications of data displays increase, while their areas of use rapidly and actively expand; new and unexpected uses specifically suited for the fresh, growing medium crop up almost daily. The animated digital display system allows for a range of applications in advertising, but also for broadcasting both targeted and general information. Flat screens are suitable for presenting audio, still pictures and moving film clips. Exhibitors may wish to accustom the information throughout the day, which is why our solutions permit data access and reconfiguration irrespective of the time of day, frequency of refreshing, importance of the data or the location's specifications. Displays can be installed almost anywhere; all community-related areas in the cityscape, but also hotels, waiting-facilities (airports, state and health facilities) and public transportation vehicles are especially befitting.</p>